Migrate exercise w02 programs to Scala 3, fix #541
lunduniversity/introprog pull request #553
Opened 2021-06-25 09:14 UTC by kuleshmaria

New:
indentation subtask in exercise 4
javap from terminal in exercise 18

2021-06-27 19:19 UTC, bjornregnell requested changes

2021-06-27 19:19 UTC, bjornregnell commented on quiz/QuizData.scala
> +      "programargument" -> "kan överföras via parametern args i en primitiv main",
You can also give params to an @main functions. So remove "primitiv" and perhaps better with "till" instead of "i"

2021-06-28 15:20 UTC, kuleshmaria commented
Fixed!
I thought based on the discussion about the Scala 3 installation the other day.
I tested the exercises in the chapter with a Scala 3 installation from binaries, but the commands for compiling and REPL are a little different with Coursier?

2021-06-28 19:25 UTC, bjornregnell commented
Yes unfortunately they are called `scala3-repl` and `scala3-compiler` and there is no app runner (!) -- I have hopes they will fix it so let's wait a bit before we change everything. I think `cursier` needs some significant resources or we need a better scala runner that can hide coursier in the background or something. Esp. support on Windows is bad which is bad. Let's wait and see until mid august. Let me know when you think this is ready for merge again.

2021-06-28 19:33 UTC, kuleshmaria commented
Hope so, otherwise I think it is ready for merge!

2021-06-28 19:45 UTC, merged