Migrate exercise w01 to Scala 3, fix #540
lunduniversity/introprog pull request #556
Opened 2021-06-27 10:02 UTC by theolundqvist

2021-06-27 19:24 UTC, bjornregnell requested changes

2021-06-27 19:24 UTC, bjornregnell commented on slides/body/lect-w01-about.tex
> +\TODO double check this
Normally I let people themselves provide a PR as a check that they want to be public with their name. So better only put your own name here and I'll remind all that they can get their name here if they want and come with a PR.

2021-06-28 07:32 UTC, theolundqvist commented
@bjornregnell Removed names

2021-06-28 09:02 UTC, bjornregnell approved these changes

2021-06-28 09:03 UTC, merged