irritext suggestions for how to start #479
lunduniversity/introprog pull request #645
Opened 2022-08-19 08:35 UTC by marcusklang

Ett förslag på tips för att komma igång, något omformulerat från det initiala förslaget.

Är något kluven till "Börja enkelt" förslaget, det kan få en effekt som vi inte önskar?

2022-08-20 12:18 UTC, bjornregnell requested changes

2022-08-20 12:18 UTC, bjornregnell commented on compendium/modules/w03-functions-lab.tex
> +\item Skapa en katalog som innehåller en scala kodfil med valfritt namn.
scala-kodfil är ett ord på svenska

2022-08-20 12:18 UTC, bjornregnell commented on compendium/modules/w03-functions-lab.tex
> +\item Skriv en primitiv main-metod i den nyskapade kodfilen som endast skriver ut strängen \code{"Hello World!"}.
ta bort "primitiv" (ev. använda ordet enkel i stället för priimtiv som ju har en speciell betydelse som tex primtiv typ etc) och ev. skriv snabel-a framför main alltså \code{@main}-metod

2022-08-20 12:18 UTC, bjornregnell commented on compendium/modules/w03-functions-lab.tex
> +\item Börja enkelt, försök att välja funktionalitet som du tror kräver mindre kod. Ett tips är att alltid försöka formulera vad ditt program ska göra (\emph{psuedokod}) som kommentarer innan du skriv
kanske ta bort perentes runt pseudokod och skriva med framför så blir meningen lättare att läsa

2022-08-20 12:18 UTC, bjornregnell commented on compendium/modules/w03-functions-lab.tex
> +\item Ett trick för att få en känsla av att det går framåt är försöka komma in i en \emph{förbättringsloop}. Konkret innebär det försöka kompilera och köra vid varje tillägg istället för att göra mån
Bra att förklara att om man kompilerar efeter varje ändring så slipper man onödiga följdfel som kan vara svåra att reda ut. Kanske förenkla och förkorta texten genom att i stället skriva typ:
```
\item Kompilera och kör vid varje tillägg och håll varje tillägg så litet som möjligt, så slipper du reda ut en massa svåra följdfel vid kompilering och eventuella körtidsfel blir mer begripliga.  
```

2022-08-20 12:18 UTC, bjornregnell commented on compendium/modules/w03-functions-lab.tex
> +\item Fortsätt utöka tills kraven för labben har uppnåtts.
Nog bäst att ta bort denna punkt så att de inte förleds att ge upp efter minimikraven -- vi vill ju stimulera till att gå vidare baserat på ambition, ork och motivation... (Tipsen handlar ju om att komma igång, inte när det är klart...)

2022-08-20 12:19 UTC, bjornregnell commented
Toppen att införa tips att komma igång! De flesta av mina kommentarer är förslag snarare än måsten. 
(I just realized that I happened to write in Swedish, but I'll do my reviews in English next time ;) )

2022-08-20 12:22 UTC, bjornregnell commented
Vi behöver bli klara med pdf till tryck i helgen och jag vill gärna ha med ditt bidrag i tryck så om du inte har möjlighet att fixa mina  kommentarer ovan i helgen så hojta så mergar jag som det är och fixar dem själv under söndagen.

2022-08-21 10:21 UTC, marcusklang commented on compendium/modules/w03-functions-lab.tex
> +\item Skapa en katalog som innehåller en scala kodfil med valfritt namn.
Ändrat i ny commit, till scala-kodfil

2022-08-21 10:22 UTC, marcusklang commented on compendium/modules/w03-functions-lab.tex
> +\item Skriv en primitiv main-metod i den nyskapade kodfilen som endast skriver ut strängen \code{"Hello World!"}.
Fixat och jag valde @ lösningen.

2022-08-21 10:22 UTC, marcusklang commented on compendium/modules/w03-functions-lab.tex
> +\item Börja enkelt, försök att välja funktionalitet som du tror kräver mindre kod. Ett tips är att alltid försöka formulera vad ditt program ska göra (\emph{psuedokod}) som kommentarer innan du skriv
Kortade ner och ändrade till börja enkelt och försök...

2022-08-21 10:23 UTC, marcusklang commented on compendium/modules/w03-functions-lab.tex
> +\item Ett trick för att få en känsla av att det går framåt är försöka komma in i en \emph{förbättringsloop}. Konkret innebär det försöka kompilera och köra vid varje tillägg istället för att göra mån
Din version är mycket bättre, jag tog denna rakt av.

2022-08-21 10:23 UTC, marcusklang commented on compendium/modules/w03-functions-lab.tex
> +\item Fortsätt utöka tills kraven för labben har uppnåtts.
Jag gjorde så att jag bevarade "Börja enkelt", men tag bort välj funktionallitet som du tror kräver mindre kod.

2022-08-21 10:27 UTC, bjornregnell approved these changes

2022-08-21 10:39 UTC, merged